version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install -r requirements_dev.txt
    finally:
      - mypy src
      - pytest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      # update the following line with your own region.
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 291621539275.dkr.ecr.us-west-2.amazonaws.com
      # Your image tag name must always be lowercase.
      - IMAGE_TAG=test_tag
      - REPOSITORY_URI=291621539275.dkr.ecr.us-west-2.amazonaws.com/district_prod_archive_flat_files
      - docker --version
  build:
    commands:
      - echo $REPOSITORY_URI:$IMAGE_TAG
      - docker build -t $IMAGE_TAG .
      - docker tag $IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG